# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# kubestuff
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
source <(kubectl completion bash)
PATH=$PATH:/usr/local/bin

# LINSTOR interactive shell
# adjust for namespace if changed (default: "linbit-sds")
alias linstor_k8s='kubectl exec -it -n linbit-sds deployments/linstor-controller -- linstor'
