apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linbit-sds
resources:
  - https://github.com/LINBIT/linstor-operator-builder//deploy/default?ref=v2.1.1&depth=1&timeout=90s
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: drbdio-pull-secret
    type: kubernetes.io/dockerconfigjson
    literals:
      - .dockerconfigjson={"auths":{"drbd.io":{"username":"{{ lb_user }}","password":"{{ lb_pass }}"}}}
