{% for node in groups['potato'] %}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "linstor-csi-lvm-thin-r{{loop.index}}"
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "{{loop.index}}"
  storagePool: "lvm-thin"
reclaimPolicy: Delete
{% endfor %}
